### ISSUE TITLE
Cannot specify decimal timeouts

### ISSUE THREAD

**Issue by madestroIT** [taxjar/taxjar.net#13]
The client's timeout property is of type int. It gets multiplied internally by 1000 to convert to milliseconds.

This is a limitation as it does not allow me to set a timeout of 1.5 seconds (1500 milliseconds).

The property should be more flexible (e.g. TimeSpan).

**Comment by fastdivision** [comment]
@madestroIT Good feedback, I'll change this in our next major release (v3). The good news is that I'm releasing async methods soon so I'll just bundle it with that. Thank you!

**Comment by fastdivision** [comment]
Fixed in #16
