### ISSUE TITLE
Request entity examples

### ISSUE THREAD

**Issue by fastdivision** [taxjar/taxjar.net#17]
Our README examples mainly use anonymous types to pass data for API requests. Let's add new examples using request entities so the data is easier to manage prior to passing it to a client method.

**Comment by digentltd** [comment]
Added more examples to README that use Entities in my pull request.

Hopefully will help somebody to understand how to do it without using anonymous types

**Comment by fastdivision** [comment]
Merged #21, making additional tweaks.
