### ISSUE TITLE
.net core compatible package is not available

### ISSUE THREAD

**Issue by tetious** [taxjar/taxjar.net#2]
Please consider adding support for .net core on nuget either via a .netstandard1.x or PCL target.

**Comment by fastdivision** [comment]
I'll try to get around to this in the very near future :-) Appreciate the feedback!

**Comment by stephen-cernota** [comment]
Any updates on this?

**Comment by stephen-cernota** [comment]
I found a .NET Core NuGet package for RestSharp, not sure if it is legit:
https://www.nuget.org/packages/restsharp.netcore/105.2.3

Ill report back if I get things to work

**Comment by stephen-cernota** [comment]
The only problem I ran into was that this restsharp.netcore package didnt have .Execute() function and I had to use .ExecuteAsync(), Im still not fully comfortable with asynchronous functionality, please anyone help if you can, but the below code is working for me so far:

`var resTask = GetResponseContentAsync(req);
            var res = resTask.Result;`

`Task<IRestResponse> GetResponseContentAsync(IRestRequest request)
        {
            var tcs = new TaskCompletionSource<IRestResponse>();
            this.apiClient.ExecuteAsync(request, response => {
                tcs.SetResult(response);
            });
            return tcs.Task;
        }`

**Comment by fastdivision** [comment]
@stephen-cernota I have a WIP branch for a .NET Core client that I'll add as a PR shortly. The only thing remaining is updating all of the specs to use a new HTTP mocking library. You should be able to use `Execute()` with the latest version of RestSharp (106.x). RestSharp.NetCore on NuGet is an **unofficial** package and out of date, I would avoid using it.

**Comment by stephen-cernota** [comment]
Awesome! Thank you!

**Comment by claytondus** [comment]
I have also written a fully async .NET Standard library for TaxJar, Claytondus.TaxJar, based on Flurl.Http. I take PRs for missing features (I am not aware of any) or bugs.
https://github.com/claytondus/Claytondus.TaxJar

**Comment by fastdivision** [comment]
.NET Core support added in #7, releasing v2.0 shortly!
