### ISSUE TITLE
Need help with generic error troubleshooting

### ISSUE THREAD

**Issue by twilly86** [taxjar/taxjar.net#22]
Taxjar.TaxjarException: 'Unprocessable Entity - Something could not be processed'

I'm getting this generic error when creating an error.

Is there any way to get more info to help with troubleshooting?

Is there a way to expose the raw request and raw response so I could paste that into PostMan and troubleshoot?

Running off V3 now.

Thanks for your help!

**Comment by fastdivision** [comment]
Hi @twilly86, that 422 error usually occurs when attempting to create an order or refund transaction that already exists in TaxJar: https://developers.taxjar.com/api/reference/#422-unprocessable-entity

When catching that exception you could look at the exception `StatusCode` and attempt to update the transaction instead if you're not tracking when the transaction was originally created.

Good question on the raw request / response for troubleshooting. We use RestSharp under the hood and there's a [couple suggestions here](https://stackoverflow.com/questions/15683858/restsharp-print-raw-request-and-response-headers) such as [Fiddler](https://www.telerik.com/fiddler) or [network tracing](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing). If you continue to have issues, feel free to reach out to our [support team](mailto:support@taxjar.com) with your TaxJar account email and we'll review your incoming API requests to see what's wrong.

**Comment by twilly86** [comment]
yup that was the issue, thanks for your help!
