### ISSUE TITLE
RatesForLocation chokes on EU countries

### ISSUE THREAD

**Issue by HopesOblivion** [taxjar/taxjar.net#25]
Using the example provided here: https://developers.taxjar.com/api/reference/#get-show-tax-rates-for-a-location 

Throws the following: 

InvalidCastException: Null object cannot be converted to a value type.
System.Convert.ChangeType(object value, Type conversionType, IFormatProvider provider)

JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'rate.super_reduced_rate', line 1, position 34.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType) in JsonSerializerInternalReader.cs, line 989

props maybe need to be marked as nullable?

**Comment by declare** [comment]
@fastdivision can someone check it please? Should be a simple fix. Thanks a lot.

**Comment by fastdivision** [comment]
Thanks for reporting this @HopesOblivion, looks like some recent updates we made to `/v2/rates` has caused our API to return null values instead of `0.0` for these attributes. I'll make a fix to our API client and inform our engineering team about the issue to make a direct fix in our API.
