### ISSUE TITLE
TaxJar not loading

### ISSUE THREAD

**Issue by daudirsch** [taxjar/taxjar.net#28]
We have a .net core 2 project that we are having issues with TaxJar running on our servers but not our local developer machines.  We are getting "could not load TaxJar" because file can't be found.  The file is clearly on the server along with all other dependencies.  We have uninstalled/re-installed the package.  We have insured we have the latest version (3.0.2).  The server only has .net core installed.  Are there any other dependencies or requirements for deployment?

**Comment by fastdivision** [comment]
Hi @daudirsch, are you getting a "could not load file or assembly error" on production? Can you share the exact error you're receiving so we can take a closer look? If this information is sensitive, feel free to send an email to support@taxjar.com. Thank you!

**Comment by daudirsch** [comment]
We are using your sandbox environment (https://api.sandbox.taxjar.com) from our servers.  It works from our local dev computers, but not our hosted servers.  Which makes me think something's not installed on our hosted server that TaxJar needs.  We used nuget to add TaxJar to our project.

The error is:
System.IO.FileNotFoundException: Could not load file or assembly 'TaxJar, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'TaxJar, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'

File on our server.
![image](https://user-images.githubusercontent.com/5702392/54686724-f207a980-4ae7-11e9-84e9-6474b697c8bf.png)

**Comment by daudirsch** [comment]
Anything on this?

**Comment by fastdivision** [comment]
This issue was discussed further over email. We had some difficulty determining the exact problem, but it looks like it may have been resolved. @daudirsch If there's an underlying issue with our API client please re-open this issue. Thank you!
