### ISSUE TITLE
Use Inheritance for some models

### ISSUE THREAD

**Issue by recheej** [taxjar/taxjar.net#3]
The Breakdown object has Shipping and LineBreadowns. All 3 of these objects have very similar properties. The common properties be put into a BaseBreakdown and individual breakdowns (Shipping, Line) could inherit. Any reason this couldn't be done?

**Comment by fastdivision** [comment]
@recheej This is a good idea. We have some minor differences in the attribute names among the 3 breakdowns that we hope to fix in a future iteration of our API, e.g. `state_tax_rate` vs. `state_sales_tax_rate` and `state_tax_collectable` vs. `state_amount`. I tried this out and it's definitely an improvement, with the added benefit of seeing these differences.

I'll get a PR up shortly. Thanks for the feedback!
