### ISSUE TITLE
.Net Standard DLLs not Updated in NuGet

### ISSUE THREAD

**Issue by brprigge** [taxjar/taxjar.net#40]
The binaries for 3.2.0 on NuGet for .Net Standard are Assembly version 3.1.1 and are referencing RestSharp 106.6.9, but the package installs RestSharp 106.10.1.  In the absence of proper Assembly Redirection in .Net Core, this is a large issue.  3.2.0 is not working in .Net Core.

![image](https://user-images.githubusercontent.com/2874155/76230147-458b6f80-61f1-11ea-865a-c292a3c195bb.png)

**Comment by ScottRudiger** [comment]
Thank you for bringing this to our attention @brprigge. We'll be releasing a patched version, `3.2.1` shortly.

**Comment by ScottRudiger** [comment]
OK, apologies for the bad release! [Version 3.2.1](https://www.nuget.org/packages/TaxJar/3.2.1) is now available.

**Comment by brprigge** [comment]
Confirmed working.  Thanks!
