### ISSUE TITLE
Tax to collect is always 0 no matter what the address or state is for an order

### ISSUE THREAD

**Issue by ChristineGr** [taxjar/taxjar.net#45]
With TaxForOrderAsync using either of the Product Tax Codes 20010 or 20041, the amount to collect is always 0.
Any idea why? We have tried several states.

**Comment by codymullins** [comment]
Hi @ChristineGr,

Can you confirm you have enabled the specific Nexus states in your TaxJar account? Currently, it is not clear when the tax amount is zero due to not having Nexus.

If this doesn't work, could you send a repro. with a sample that does not work?

Thank you!
