### ISSUE TITLE
RestSharp dependency

### ISSUE THREAD

**Issue by TBeblar** [taxjar/taxjar.net#57]
Requesting validation of RestSharp latest, 108.0.1, and update of package references.

**Comment by TBeblar** [comment]
This is becoming a problem:
![image](https://user-images.githubusercontent.com/24417753/200670192-ac1b0e4c-5092-4aeb-a637-13f7f16e64ea.png)

**Comment by DonWMason** [comment]
> This is becoming a problem: ![image](https://user-images.githubusercontent.com/24417753/200670192-ac1b0e4c-5092-4aeb-a637-13f7f16e64ea.png)

Agreed! Can we get an update to the current version of RestSharp please.

**Comment by ripvannwinkler** [comment]
So.. is TaxJar dead or?

**Comment by TBeblar** [comment]
> So.. is TaxJar dead or?

It hasn't been updated in 2 years but the support team does still answer emails. Not sure if they are planning to maintain this project going forward but it would be nice to know.

**Comment by TBeblar** [comment]
Ok, this is starting to become a big problem for us. Can some devs responded to this or should our company start looking to alternative tax calc providers?

**Comment by gbanuk2** [comment]
Any update on TaxJar being updated to a newer version of RestSharp? It's starting to cause compatibility issues with our code base.
