### ISSUE TITLE
x-api-version support?

### ISSUE THREAD

**Issue by pwhe23** [taxjar/taxjar.net#58]
I received an email from TaxJar indicating that we need to start using the "x-api-version" header but it doesn't appear this SDK supports it.

https://support.taxjar.com/article/1060-how-do-i-use-the-latest-version-of-the-taxjar-api

Is this .Net Nuget SDK still supported?

**Comment by breaker05** [comment]
I solved this by simply passing in the header after initializing the client.

`var _client = new TaxjarApi("Your_Token");`
`_client.SetApiConfig("headers", new Dictionary<string, string> {
    { "x-api-version", "2022-01-24" }
  });`

**Comment by pwhe23** [comment]
I just got an email back from support so I totally misunderstood the email. The "x-api-version" header is optional and the way you're passing it via headers in the config makes a lot of sense, thanks!
